<?php

declare(strict_types=1);

namespace Paylod\Tests;

use Paylod\DarajaCatalog;
use Paylod\Scripts\DarajaCatalogVerifier;
use PHPUnit\Framework\TestCase;
use RuntimeException;

require_once __DIR__ . '/../scripts/DarajaCatalogVerifier.php';

/**
 * The vendored Daraja catalog is a COPY. Copies drift, and a drifted copy of this particular table
 * is what shipped the 4999 "false failure / double charge" bug twice. These guards make the drift
 * mechanical rather than discovered-by-customer.
 *
 * THIS GUARD NEVER SKIPS. It used to: the canonical table lives in a private monorepo, and when
 * that monorepo was not checked out beside this repo the test called markTestSkipped. In CI it is
 * never checked out, so the guard skipped on every run and the pipeline stayed green while
 * verifying nothing. A check that cannot distinguish "I did not look" from "I looked and it is
 * fine" is not a check.
 *
 * What it verifies instead is `daraja-catalog.sha256`, a committed digest of the canonical bytes,
 * generated by the monorepo and shared by all four SDKs. It needs no sibling checkout, no network
 * and no credential - which is exactly why it was preferred over an MPESA_REPO_TOKEN secret that
 * would have put long-lived private-monorepo read access into three public repos.
 *
 * The sibling-monorepo comparison survives as an ADDITIONAL, stronger check for developers who do
 * have the monorepo. Its absence downgrades nothing.
 */
final class DarajaCatalogDriftTest extends TestCase
{
    private const CHECKSUM = __DIR__ . '/../daraja-catalog.sha256';

    private static function verifier(): DarajaCatalogVerifier
    {
        return new DarajaCatalogVerifier(dirname(__DIR__));
    }

    /**
     * The guard proper. Always verifies the pinned digests; additionally compares against the
     * canonical file when the monorepo is present. Never skips.
     */
    public function testVendoredCatalogMatchesItsPinnedDigest(): void
    {
        $log = self::verifier()->verify();

        self::assertNotEmpty($log, 'the drift guard must report what it actually verified');
        self::assertNotEmpty(
            array_filter($log, static fn (string $l): bool => str_starts_with($l, '[ok] pinned digest matches')),
            "the pinned-checksum verification must have run.\n" . implode("\n", $log)
        );
    }

    /** The pinned file must pin something real - at least one row, for the vendored catalog. */
    public function testPinnedChecksumFilePinsTheVendoredCatalog(): void
    {
        $rows = self::verifier()->pinnedRows();

        self::assertNotEmpty($rows, 'daraja-catalog.sha256 must contain at least one data row');
        self::assertContains(
            'src/resources/daraja-error-codes.json',
            array_column($rows, 'vendoredRel'),
            'daraja-catalog.sha256 must pin the vendored Daraja catalog'
        );
    }

    /**
     * THE CI CONDITION. With no monorepo anywhere in sight the guard must still pass AND must still
     * have verified something - the old behaviour (skip, exit green) is what this whole change
     * exists to kill.
     */
    public function testGuardStillVerifiesWithANonexistentMonorepo(): void
    {
        self::withEnv('MPESA_REPO', '/nonexistent', static function (): void {
            $verifier = self::verifier();
            self::assertFalse($verifier->monorepoIsPresent(), 'precondition: no monorepo');

            $log = $verifier->verify();
            self::assertNotEmpty(
                array_filter($log, static fn (string $l): bool => str_starts_with($l, '[ok] pinned digest matches')),
                'without a monorepo the guard must still perform the pinned-checksum verification'
            );
        });
    }

    /**
     * FAIL-CLOSED. Every way the pinned file can be useless must make the guard RED, because a
     * guard that degrades to "pass" when its own input is broken is the exact failure being fixed.
     *
     * @dataProvider brokenChecksumFiles
     */
    public function testGuardFailsClosedOnABrokenChecksumFile(?string $contents, string $why): void
    {
        self::withChecksumFile($contents, function () use ($why): void {
            // NOTE: the verdict is recorded here and asserted OUTSIDE the catch. PHPUnit's own
            // AssertionFailedError extends RuntimeException, so a `self::fail()` inside the `try`
            // would be swallowed by the `catch` below and this test would pass no matter what -
            // exactly the vacuity it is here to prevent. The non-vacuity harness caught it.
            $message = null;
            try {
                self::verifier()->verify();
            } catch (RuntimeException $e) {
                $message = $e->getMessage();
            }

            self::assertIsString(
                $message,
                "the drift guard passed with a {$why} checksum file; it must fail closed"
            );
            self::assertNotSame('', $message, 'a fail-closed guard must say why it failed');
        });
    }

    /** @return array<string, array{0: ?string, 1: string}> */
    public static function brokenChecksumFiles(): array
    {
        $good = '2046f95cda940b8e1522c71646c1a76c8d97aefbc820ad671fbe006a87f3700b';
        $header = "# comment\n";

        return [
            'missing' => [null, 'missing'],
            'empty' => ['', 'empty'],
            'comments only' => ["# nothing but comments\n#\n", 'zero-data-row'],
            'too few fields' => ["{$header}{$good}  {$good}  only-three-fields\n", 'short-row'],
            'too many fields' => ["{$header}{$good}  {$good}  a  b  c\n", 'long-row'],
            'canonical digest not hex' => ["{$header}zz  {$good}  a  b\n", 'non-hex-canonical'],
            'vendored digest too short' => ["{$header}{$good}  abc123  a  b\n", 'short-digest'],
            'uppercase digest' => [
                "{$header}" . strtoupper($good) . "  {$good}  a  b\n",
                'uppercase-digest',
            ],
        ];
    }

    /** A pinned row naming a file that is not there must fail, not be quietly ignored. */
    public function testGuardFailsWhenAPinnedFileIsMissing(): void
    {
        $good = '2046f95cda940b8e1522c71646c1a76c8d97aefbc820ad671fbe006a87f3700b';
        $contents = "# comment\n{$good}  {$good}  canonical/nope.json  src/resources/does-not-exist.json\n";

        self::withChecksumFile($contents, function (): void {
            $this->expectException(RuntimeException::class);
            self::verifier()->verifyPinned();
        });
    }

    /**
     * And the drift the guard is actually for: a vendored copy whose bytes no longer hash to the
     * pinned digest. Verified with NO monorepo available, because that is the CI shape - the old
     * guard would have skipped here and reported success.
     */
    public function testGuardFailsOnADriftedVendoredCopyEvenWithNoMonorepo(): void
    {
        self::withEnv('MPESA_REPO', '/nonexistent', function (): void {
            $vendored = dirname(__DIR__) . '/src/resources/daraja-error-codes.json';
            $original = file_get_contents($vendored);
            self::assertIsString($original);

            try {
                file_put_contents($vendored, $original . "\n");
                $this->expectException(RuntimeException::class);
                self::verifier()->verifyPinned();
            } finally {
                file_put_contents($vendored, $original);
            }
        });
    }

    /**
     * Run $body with the checksum file replaced by $contents (null = removed), restoring the real
     * file afterwards no matter what. A guard test that can leave the repo dirty is its own bug.
     */
    private static function withChecksumFile(?string $contents, callable $body): void
    {
        $original = file_get_contents(self::CHECKSUM);
        self::assertIsString($original, 'the real daraja-catalog.sha256 must exist before we swap it');

        try {
            if ($contents === null) {
                unlink(self::CHECKSUM);
            } else {
                file_put_contents(self::CHECKSUM, $contents);
            }
            $body();
        } finally {
            file_put_contents(self::CHECKSUM, $original);
        }
    }

    private static function withEnv(string $name, string $value, callable $body): void
    {
        $previous = getenv($name);

        try {
            putenv("{$name}={$value}");
            $body();
        } finally {
            if ($previous === false) {
                putenv($name);
            } else {
                putenv("{$name}={$previous}");
            }
        }
    }

    /**
     * (code, family) is the real key. `code` alone is ambiguous - three codes appear under two
     * different families with materially different meanings, and in one case with opposite
     * `retryable` verdicts. A duplicate (code, family) PAIR, by contrast, is a catalog bug: it
     * would make lookup order-dependent.
     */
    public function testEveryCodeFamilyPairIsUnique(): void
    {
        $seen = [];
        foreach (DarajaCatalog::allEntries() as $entry) {
            $pair = (string) $entry['code'] . '|' . (string) ($entry['family'] ?? '');
            self::assertArrayNotHasKey(
                $pair,
                $seen,
                "duplicate (code, family) pair in the Daraja catalog: {$pair}"
            );
            $seen[$pair] = true;
        }

        self::assertSame(
            count(DarajaCatalog::allEntries()),
            count($seen),
            'every catalog entry must contribute a distinct (code, family) pair'
        );
    }

    /**
     * Non-vacuity for the guard above. If the catalog had no duplicate bare `code` values at all,
     * the uniqueness assertion would be trivially true and would document nothing. This test pins
     * the ambiguity that makes (code, family) the necessary key.
     */
    public function testDuplicateBareCodesDoExist(): void
    {
        $byCode = [];
        foreach (DarajaCatalog::allEntries() as $entry) {
            $byCode[(string) $entry['code']][] = (string) ($entry['family'] ?? '');
        }

        // PHP coerces numeric-string array keys to integers, so cast back before comparing.
        $duplicated = array_map(
            'strval',
            array_keys(array_filter($byCode, static fn (array $f): bool => count($f) > 1))
        );
        sort($duplicated);

        // These three are the reason `code` alone cannot be the key.
        self::assertSame(['0', '2001', '500.001.1001'], $duplicated);

        // Each collision is split across the STK surface and exactly one non-STK surface.
        $expectedFamilies = [
            '0' => ['b2c_c2b_result', 'stk_result'],
            '2001' => ['b2c_c2b_result', 'stk_result'],
            '500.001.1001' => ['api_error', 'stk_result'],
        ];
        foreach ($duplicated as $code) {
            $families = $byCode[$code];
            sort($families);
            self::assertSame(
                $expectedFamilies[$code],
                $families,
                "code {$code} is expected to be split across the STK and non-STK surfaces"
            );
        }
    }

    /**
     * `errorCatalog()` is a code-keyed convenience view and therefore CANNOT represent the
     * ambiguity above. Its documented collision rule is "STK wins", because STK is the payment
     * path. Changing that shape would be a breaking API change, so it is pinned here instead:
     * silent reordering of the JSON must not silently flip which entry a caller sees.
     */
    public function testErrorCatalogResolvesCollisionsToTheStkEntry(): void
    {
        $catalog = DarajaCatalog::errorCatalog();

        // 2001: STK = wrong PIN (customer, retryable). b2c_c2b = initiator credential failure.
        self::assertSame('customer', $catalog['2001']['category']);
        self::assertTrue($catalog['2001']['retryable']);
        self::assertSame('stk_result', $catalog['2001']['family']);

        // 500.001.1001: STK = pending. api_error = terminal mpesa_system error.
        self::assertSame('pending', $catalog['500.001.1001']['category']);
        self::assertSame('stk_result', $catalog['500.001.1001']['family']);

        // 0: success on both surfaces, but still resolved STK-first.
        self::assertSame('stk_result', $catalog['0']['family']);
    }
}
